language: python
python:
  - "3.6"
cache: pip3

install:
  - pip3 install -r requirements.txt
  - pip install coveralls

services:
  - postgresql
before_script:
  - psql -c 'create database ridemyway;' -U postgres
  - psql -c 'create database testdb;' -U postgres
  - psql -c "ALTER USER postgres PASSWORD 'postgres' ;" -U postgres
  - cd api/database
  - python db.py
  - cd ../..
script:
    - coverage run -m unittest
    - coverage report
after_success:
    - coveralls
