language: python
python:
  - "3.6"
  
cache: pip
  
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install flask_jwt_extended

# command to run tests
script:
  - python -m pytest test/
  - coverage report

  
after_success:
  - coveralls